# Generated by Django 4.0.4 on 2022-05-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_testkitchenpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestKitchenPost',
        ),
    ]
