# Generated by Django 4.0.4 on 2022-05-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_testkitchenpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('sent_to', models.CharField(max_length=50)),
                ('received', models.BooleanField(default=False)),
                ('received_from', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
