# Generated by Django 4.0.4 on 2022-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recipecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecollection',
            name='received',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipecollection',
            name='received_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipecollection',
            name='sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipecollection',
            name='sent_to',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
