# Generated by Django 4.0.4 on 2022-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipe_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='./media_cdn'),
            preserve_default=False,
        ),
    ]
