# Generated by Django 4.0.4 on 2022-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='secondary_color',
            field=models.CharField(default='var(--main-red)', max_length=100),
        ),
    ]
